language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

    exclude:
        - php: hhvm
          env: PHP_BIN=php-cgi

    include:
        - php: 5.5
          env: dependencies="--prefer-lowest --prefer-stable" PHP_BIN=php

script:
    - vendor/bin/tester -p $PHP_BIN tests -s
    - php code-checker/src/code-checker.php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer update --no-interaction --prefer-source $dependencies
    - composer create-project nette/code-checker code-checker ~2.3 --no-interaction --prefer-source
