language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

env:
    - TESTER_PHP_BIN=php
    - TESTER_PHP_BIN=php-cgi

matrix:
    allow_failures:
        - php: 7.0
          env: COVERAGE=on

    include:
        - php: 7.0
          env: COVERAGE=on

script:
    - src/tester -p $TESTER_PHP_BIN --info
    - src/tester -p $TESTER_PHP_BIN tests -s $COVERAGE_ARGS
    - src/tester -p $TESTER_PHP_BIN -o none tests/fail.phptx; if [ $? -eq 0 ]; then echo "tests/fail.phptx SHOULD FAIL"; exit 1; else echo "fail checked"; fi;
    - php code-checker/src/code-checker.php --no-progress --short-arrays

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    - travis_retry composer create-project nette/code-checker code-checker ~2.5 --no-interaction
    - if [ "$COVERAGE" == "on" ]; then TESTER_PHP_BIN=phpdbg; COVERAGE_ARGS="--coverage ./coverage.xml --coverage-src ./src"; fi

after_script:
    # Report Code Coverage
    - >
      if [ "$COVERAGE" == "on" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true; fi

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
