language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

matrix:
    include:
        - php: 7.1
          env: codingStandard=on

script:
    - if [ "$PHP_BIN" ]; then vendor/bin/tester -p $PHP_BIN tests -s; fi
    - >
      if [ "$codingStandard" ]; then
      php temp/code-checker/src/code-checker.php --short-arrays
      && php temp/coding-standard/ecs check src tests examples tools --config tests/coding-standard.neon
      && ./node_modules/.bin/eslint "src/**/*.js";
      fi

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester
    - travis_retry composer install --no-interaction --prefer-dist
    # Install Code Checkers, new Node.js and Eslint
    - >
      if [ "$codingStandard" ]; then
      travis_retry composer create-project nette/code-checker temp/code-checker ~2 --no-interaction;
      travis_retry composer create-project nette/coding-standard temp/coding-standard --no-interaction;

      . $HOME/.nvm/nvm.sh;
      nvm install stable;
      nvm use stable;
      npm install;
      npm install eslint;
      fi

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
