language: php
php:
    - 7.1

matrix:
    include:
        - php: 7.0
          env: coverage=on

    allow_failures:
        - php: 7.0
          env: coverage=on

script:
    - vendor/bin/tester tests -s -p php $coverageArgs
    - php code-checker/src/code-checker.php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - travis_retry composer install --no-interaction --prefer-dist
    - travis_retry composer create-project nette/code-checker code-checker ~2.5 --no-interaction
    - if [ "$coverage" ]; then coverageArgs="-p phpdbg --coverage ./coverage.xml --coverage-src ./src"; fi

after_script:
    # Report Code Coverage
    - >
      if [ "$coverage" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml;
      fi

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
