language: php

script:
    - php code-checker/src/code-checker.php

before_script:
    - travis_retry composer create-project nette/code-checker code-checker ~2.5 --no-interaction

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
