language: php
php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

    include:
        - php: 5.6
          env: dependencies="--prefer-lowest --prefer-stable"

script:
    - vendor/bin/tester tests -s -p php -c tests/php-unix.ini
    - php temp/code-checker/src/code-checker.php --short-arrays -i netteForms
    - if [ $TRAVIS_PHP_VERSION  == "5.6" ]; then grunt --gruntfile tests/netteForms/Gruntfile.js test; fi

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - travis_retry composer update --no-interaction --prefer-dist $dependencies
    - travis_retry composer create-project nette/code-checker temp/code-checker ~2.5 --no-interaction
    - if [ $TRAVIS_PHP_VERSION  == "5.6" ]; then npm install -g grunt-cli; cd tests/netteForms; npm install; bower install; cd ../..; fi
  
sudo: false

cache:
    directories:
        - $HOME/.composer/cache
