language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

script:
    - vendor/bin/tester tests -s -p php -c tests/php-unix.ini
    - php code-checker/src/code-checker.php -i netteForms
    - if [ $TRAVIS_PHP_VERSION  == "5.6" ]; then grunt --gruntfile tests/netteForms/Gruntfile.js test; fi

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer install --no-interaction --dev --prefer-source
    - composer create-project nette/code-checker code-checker ~2.3 --no-interaction --prefer-source
    - if [ $TRAVIS_PHP_VERSION  == "5.6" ]; then npm install -g grunt-cli; cd tests/netteForms; npm install; bower install; cd ../..; fi
